# -*- coding: utf-8 -*-
"""Conceitos Basicos de Estatistica com Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OeIPQRuW81Heol568v71gBsCf_FmKSBA
"""

import pandas as pd
from pathlib import Path



# Define o caminho completo para o arquivo Excel
ARQUIVO_CLIENTES_COMPLETO = Path('/content/Dados/insurance.csv')

# Se precisar do diretório, você pode obtê-lo a partir do caminho completo do arquivo
DIRETORIO_DO_ARQUIVO = ARQUIVO_CLIENTES_COMPLETO.parent

# Lê o arquivo Excel usando o caminho completo e correto
df = pd.read_csv(ARQUIVO_CLIENTES_COMPLETO)




df.head()

# df.sample(5)

fr = df['sex'].value_counts().reset_index(name='frequencia absoluta').set_index('sex')\

fr.index.name = None
fr.columns.name = 'SEXO'

fr.head()

tabela_fr = pd.DataFrame({'Frequencia Absoluta':df['sex'].value_counts(),
                          'Frequencia Relativa': df['sex'].value_counts(normalize = True).round(4) * 100})

tabela_fr = tabela_fr.set_axis(['Masculino','Feminino'], axis='index').rename_axis('Sexo', axis='columns')

tabela_fr